# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'car_ui.ui'
#
# Created: Mon May 01 18:19:53 2017
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(553, 252)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.fr_wh_L_in_LE = QtGui.QLineEdit(self.centralwidget)
        self.fr_wh_L_in_LE.setObjectName("fr_wh_L_in_LE")
        self.gridLayout.addWidget(self.fr_wh_L_in_LE, 3, 5, 1, 1)
        self.create_btn = QtGui.QPushButton(self.centralwidget)
        self.create_btn.setObjectName("create_btn")
        self.gridLayout.addWidget(self.create_btn, 2, 4, 1, 1)
        self.bk_wh_L_in_LE = QtGui.QLineEdit(self.centralwidget)
        self.bk_wh_L_in_LE.setObjectName("bk_wh_L_in_LE")
        self.gridLayout.addWidget(self.bk_wh_L_in_LE, 1, 5, 1, 1)
        self.fr_wh_R_in_LE = QtGui.QLineEdit(self.centralwidget)
        self.fr_wh_R_in_LE.setObjectName("fr_wh_R_in_LE")
        self.gridLayout.addWidget(self.fr_wh_R_in_LE, 3, 2, 1, 1)
        self.fr_wh_L_out_LE = QtGui.QLineEdit(self.centralwidget)
        self.fr_wh_L_out_LE.setObjectName("fr_wh_L_out_LE")
        self.gridLayout.addWidget(self.fr_wh_L_out_LE, 3, 7, 1, 1)
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 7, 1, 1)
        self.bk_wh_R_out_LE = QtGui.QLineEdit(self.centralwidget)
        self.bk_wh_R_out_LE.setObjectName("bk_wh_R_out_LE")
        self.gridLayout.addWidget(self.bk_wh_R_out_LE, 1, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(100, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 4, 1, 1)
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 4, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 4, 7, 1, 1)
        self.bk_wh_R_in_LE = QtGui.QLineEdit(self.centralwidget)
        self.bk_wh_R_in_LE.setObjectName("bk_wh_R_in_LE")
        self.gridLayout.addWidget(self.bk_wh_R_in_LE, 1, 2, 1, 1)
        self.bk_wh_L_out_LE = QtGui.QLineEdit(self.centralwidget)
        self.bk_wh_L_out_LE.setObjectName("bk_wh_L_out_LE")
        self.gridLayout.addWidget(self.bk_wh_L_out_LE, 1, 7, 1, 1)
        self.fr_wh_R_out_LE = QtGui.QLineEdit(self.centralwidget)
        self.fr_wh_R_out_LE.setObjectName("fr_wh_R_out_LE")
        self.gridLayout.addWidget(self.fr_wh_R_out_LE, 3, 0, 1, 1)
        self.label_6 = QtGui.QLabel(self.centralwidget)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 4, 5, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 80, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 2, 7, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 2, 0, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 3, 4, 1, 1)
        self.label_5 = QtGui.QLabel(self.centralwidget)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 5, 1, 1)
        self.label_7 = QtGui.QLabel(self.centralwidget)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 0, 2, 1, 1)
        self.label_8 = QtGui.QLabel(self.centralwidget)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 4, 2, 1, 1)
        self.bk_wh_L_in_btn = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bk_wh_L_in_btn.sizePolicy().hasHeightForWidth())
        self.bk_wh_L_in_btn.setSizePolicy(sizePolicy)
        self.bk_wh_L_in_btn.setMaximumSize(QtCore.QSize(30, 16777215))
        self.bk_wh_L_in_btn.setObjectName("bk_wh_L_in_btn")
        self.gridLayout.addWidget(self.bk_wh_L_in_btn, 1, 6, 1, 1)
        self.fr_wh_L_in_btn = QtGui.QPushButton(self.centralwidget)
        self.fr_wh_L_in_btn.setMaximumSize(QtCore.QSize(30, 16777215))
        self.fr_wh_L_in_btn.setObjectName("fr_wh_L_in_btn")
        self.gridLayout.addWidget(self.fr_wh_L_in_btn, 3, 6, 1, 1)
        self.fr_wh_R_in_btn = QtGui.QPushButton(self.centralwidget)
        self.fr_wh_R_in_btn.setMaximumSize(QtCore.QSize(30, 16777215))
        self.fr_wh_R_in_btn.setObjectName("fr_wh_R_in_btn")
        self.gridLayout.addWidget(self.fr_wh_R_in_btn, 3, 3, 1, 1)
        self.bk_wh_L_out_btn = QtGui.QPushButton(self.centralwidget)
        self.bk_wh_L_out_btn.setMaximumSize(QtCore.QSize(30, 16777215))
        self.bk_wh_L_out_btn.setObjectName("bk_wh_L_out_btn")
        self.gridLayout.addWidget(self.bk_wh_L_out_btn, 1, 8, 1, 1)
        self.bk_wh_R_in_btn = QtGui.QPushButton(self.centralwidget)
        self.bk_wh_R_in_btn.setMaximumSize(QtCore.QSize(30, 16777215))
        self.bk_wh_R_in_btn.setObjectName("bk_wh_R_in_btn")
        self.gridLayout.addWidget(self.bk_wh_R_in_btn, 1, 3, 1, 1)
        self.fr_wh_L_out_btn = QtGui.QPushButton(self.centralwidget)
        self.fr_wh_L_out_btn.setMaximumSize(QtCore.QSize(30, 16777215))
        self.fr_wh_L_out_btn.setObjectName("fr_wh_L_out_btn")
        self.gridLayout.addWidget(self.fr_wh_L_out_btn, 3, 8, 1, 1)
        self.bk_wh_R_out_btn = QtGui.QPushButton(self.centralwidget)
        self.bk_wh_R_out_btn.setMaximumSize(QtCore.QSize(30, 16777215))
        self.bk_wh_R_out_btn.setObjectName("bk_wh_R_out_btn")
        self.gridLayout.addWidget(self.bk_wh_R_out_btn, 1, 1, 1, 1)
        self.fr_wh_R_out_btn = QtGui.QPushButton(self.centralwidget)
        self.fr_wh_R_out_btn.setMaximumSize(QtCore.QSize(30, 16777215))
        self.fr_wh_R_out_btn.setObjectName("fr_wh_R_out_btn")
        self.gridLayout.addWidget(self.fr_wh_R_out_btn, 3, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 553, 21))
        self.menubar.setObjectName("menubar")
        self.menuMenu = QtGui.QMenu(self.menubar)
        self.menuMenu.setObjectName("menuMenu")
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionHelp = QtGui.QAction(MainWindow)
        self.actionHelp.setObjectName("actionHelp")
        self.actionCheck_for_updates = QtGui.QAction(MainWindow)
        self.actionCheck_for_updates.setObjectName("actionCheck_for_updates")
        self.menuMenu.addAction(self.actionExit)
        self.menuHelp.addAction(self.actionHelp)
        self.menuHelp.addAction(self.actionCheck_for_updates)
        self.menubar.addAction(self.menuMenu.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Car Wheel Stretch Rig Window", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "BackWheel_R", None, QtGui.QApplication.UnicodeUTF8))
        self.create_btn.setText(QtGui.QApplication.translate("MainWindow", "Create Rig", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "BackWheel_L", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "FrontWheel_R", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "FrontWheel_L", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "start_pivot", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "start_pivot", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "start_pivot", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "start_pivot", None, QtGui.QApplication.UnicodeUTF8))
        self.bk_wh_L_in_btn.setText(QtGui.QApplication.translate("MainWindow", "<<", None, QtGui.QApplication.UnicodeUTF8))
        self.fr_wh_L_in_btn.setText(QtGui.QApplication.translate("MainWindow", "<<", None, QtGui.QApplication.UnicodeUTF8))
        self.fr_wh_R_in_btn.setText(QtGui.QApplication.translate("MainWindow", "<<", None, QtGui.QApplication.UnicodeUTF8))
        self.bk_wh_L_out_btn.setText(QtGui.QApplication.translate("MainWindow", "<<", None, QtGui.QApplication.UnicodeUTF8))
        self.bk_wh_R_in_btn.setText(QtGui.QApplication.translate("MainWindow", "<<", None, QtGui.QApplication.UnicodeUTF8))
        self.fr_wh_L_out_btn.setText(QtGui.QApplication.translate("MainWindow", "<<", None, QtGui.QApplication.UnicodeUTF8))
        self.bk_wh_R_out_btn.setText(QtGui.QApplication.translate("MainWindow", "<<", None, QtGui.QApplication.UnicodeUTF8))
        self.fr_wh_R_out_btn.setText(QtGui.QApplication.translate("MainWindow", "<<", None, QtGui.QApplication.UnicodeUTF8))
        self.menuMenu.setTitle(QtGui.QApplication.translate("MainWindow", "Menu", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("MainWindow", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionHelp.setText(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCheck_for_updates.setText(QtGui.QApplication.translate("MainWindow", "check for updates", None, QtGui.QApplication.UnicodeUTF8))

